// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: nexuscachepb/nexuscachepb.proto

// protoc --go-grpc_out=. --go_out=. ./nexuscachepb/nexuscachepb.proto

package nexuscachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NexusCache_Get_FullMethodName = "/nexuscachepb.NexusCache/Get"
	NexusCache_Set_FullMethodName = "/nexuscachepb.NexusCache/Set"
)

// NexusCacheClient is the client API for NexusCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NexusCacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
}

type nexusCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusCacheClient(cc grpc.ClientConnInterface) NexusCacheClient {
	return &nexusCacheClient{cc}
}

func (c *nexusCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, NexusCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusCacheClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, NexusCache_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusCacheServer is the server API for NexusCache service.
// All implementations must embed UnimplementedNexusCacheServer
// for forward compatibility.
type NexusCacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	mustEmbedUnimplementedNexusCacheServer()
}

// UnimplementedNexusCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNexusCacheServer struct{}

func (UnimplementedNexusCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedNexusCacheServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedNexusCacheServer) mustEmbedUnimplementedNexusCacheServer() {}
func (UnimplementedNexusCacheServer) testEmbeddedByValue()                    {}

// UnsafeNexusCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusCacheServer will
// result in compilation errors.
type UnsafeNexusCacheServer interface {
	mustEmbedUnimplementedNexusCacheServer()
}

func RegisterNexusCacheServer(s grpc.ServiceRegistrar, srv NexusCacheServer) {
	// If the following call panics, it indicates UnimplementedNexusCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NexusCache_ServiceDesc, srv)
}

func _NexusCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusCache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusCacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusCache_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusCacheServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NexusCache_ServiceDesc is the grpc.ServiceDesc for NexusCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexuscachepb.NexusCache",
	HandlerType: (*NexusCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _NexusCache_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _NexusCache_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexuscachepb/nexuscachepb.proto",
}
